// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkJ0A_f-XMDBVmaWrSm6uL9gQKZciyNbU',
    appId: '1:434772625503:web:12eb74845c85c5391f73ea',
    messagingSenderId: '434772625503',
    projectId: 'chair-authentication',
    authDomain: 'chair-authentication.firebaseapp.com',
    storageBucket: 'chair-authentication.appspot.com',
    measurementId: 'G-FNHRJ9WH80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANArEjukEvQPbajCiAN61JDoHiompAdTU',
    appId: '1:434772625503:android:daa880bb8de5a2a81f73ea',
    messagingSenderId: '434772625503',
    projectId: 'chair-authentication',
    storageBucket: 'chair-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_zqPEhtefIs0g4lpEPnfaBXlW39lYdHg',
    appId: '1:434772625503:ios:ccb4c48dfefbd5b41f73ea',
    messagingSenderId: '434772625503',
    projectId: 'chair-authentication',
    storageBucket: 'chair-authentication.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_zqPEhtefIs0g4lpEPnfaBXlW39lYdHg',
    appId: '1:434772625503:ios:ccb4c48dfefbd5b41f73ea',
    messagingSenderId: '434772625503',
    projectId: 'chair-authentication',
    storageBucket: 'chair-authentication.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkJ0A_f-XMDBVmaWrSm6uL9gQKZciyNbU',
    appId: '1:434772625503:web:5e4b394db876b6c71f73ea',
    messagingSenderId: '434772625503',
    projectId: 'chair-authentication',
    authDomain: 'chair-authentication.firebaseapp.com',
    storageBucket: 'chair-authentication.appspot.com',
    measurementId: 'G-K99BYVY646',
  );

}